// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEjC6oPqQng_xTuLD8lGPKrvLUiyalJ0Q',
    appId: '1:427951182285:web:afde1a7d49e5e590623484',
    messagingSenderId: '427951182285',
    projectId: 'minto-8ef08',
    authDomain: 'minto-8ef08.firebaseapp.com',
    storageBucket: 'minto-8ef08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK6wPzSsge2YYWsQZ3MFXfzz6f4EOy1RY',
    appId: '1:427951182285:android:db718ddcb184e202623484',
    messagingSenderId: '427951182285',
    projectId: 'minto-8ef08',
    storageBucket: 'minto-8ef08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdQbyF-yQsqO-ordBn1FAXqjCOoXlFO88',
    appId: '1:427951182285:ios:9c438f10d4b24c88623484',
    messagingSenderId: '427951182285',
    projectId: 'minto-8ef08',
    storageBucket: 'minto-8ef08.appspot.com',
    iosClientId: '427951182285-jja7hu4u0jvshjltqeo20pj3qsi49ekk.apps.googleusercontent.com',
    iosBundleId: 'com.ramshid.minto',
  );
}
